# Generated by Django 4.2.13 on 2024-06-24 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='invitation_code',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='otp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
