# Generated by Django 4.2.13 on 2024-06-24 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_member_invitation_code_member_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_invited',
            field=models.BooleanField(default=True),
        ),
    ]
