# Generated by Django 4.2.13 on 2024-06-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_member_is_invited'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='connections',
            field=models.ManyToManyField(blank=True, to='member.member'),
        ),
    ]
